development:
  adapter: mysql2
  encoding: utf8
  database: adopt_india_development
  username: root
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: adopt_india_test
  username: root
  password:
